name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.1
  meta: ^1.9.1
  csv: ^5.0.0
  recase: ^4.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0 
  source_gen: ^1.0.0
  flutter_sheet_localization: ^5.1.1
  build: ^2.0.0
  analyzer: ^6.2.0
  collection: ^1.15.0
  intl: ^0.17.0
  localization_builder: ^0.15.7

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^2.4.6

